#!/bin/bash
set -eux
pip_install=(
	-e .
	flake8
	mock
	pytest{,-cov,-randomly,-xdist}
	six
)
# By default, run tests with pytest-forked plugin,
# disable in terminal for debugging, you may add --forked
flag_forked="--forked"
if [[ -z "${CONTINUOUS_INTEGRATION-}" ]] && [[ -t 1 ]] ; then
	flag_forked=""
fi
test_flags=(
	$@
	$flag_forked
	tests/
)

cd "$( dirname "${BASH_SOURCE[0]}" )/.."
if [[ "${virtualenv-1}" = "0" ]] ; then
	pip install ${pip_install[@]}
	pytest ${test_flags[@]}
else
	if [[ ! -d ./venv-27 ]] ; then
		virtualenv --python=python2.7 ./venv-27
		./venv-27/bin/pip install ${pip_install[@]}
	fi
	if [[ ! -d ./venv-36 ]] ; then
		virtualenv --python=python3.6 ./venv-36
		./venv-27/bin/pip install ${pip_install[@]}
	fi
	./venv-27/bin/pytest ${test_flags[@]}
	./venv-36/bin/pytest ${test_flags[@]}
	# FIXME: too many errors
	# ./venv-27/bin/flake8 python2/
	# ./venv-36/bin/flake8 python3/ tests/
fi
rm -rf ./_httplib2_test_cache
